### ISSUE TITLE
Upgrade `phoenix.js`

### ISSUE THREAD

**Issue by dzbo** [kagemusha/ember-phoenix-channel#2]
Could you upgrade addon to use latest `phoenix.js`?

https://github.com/phoenixframework/phoenix/blob/v1.4.0-rc.1/assets/js/phoenix.js

**Comment by kagemusha** [comment]
Can you submit a PR?

**Comment by dzbo** [comment]
PR ready https://github.com/kagemusha/ember-phoenix-channel/pull/3
